services:
  - type: web
    name: ivaylo-blog
    env: node
    plan: starter # Дисковете изискват Starter план ($7/мес)
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /var/lib/data/database.sqlite
      - key: UPLOADS_PATH
        value: /var/lib/data/uploads
    disk:
      name: data
      mountPath: /var/lib/data
      sizeGB: 1
